name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger CI/CD when pushing to main

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake

      - name: Configure dbt Profile
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          data_pipeline:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: cc07163.ap-southeast-1
                user: ravethi
                password: Hunkalcoffee@123
                role: dbt_role
                warehouse: dbt_wh
                database: dbt_db
                schema: dbt_schema
                threads: 4
          EOF

      - name: Set DBT_PROFILES_DIR
        run: echo "DBT_PROFILES_DIR=$HOME/.dbt" >> $GITHUB_ENV

      - name: Run dbt Tests
        run: |
          dbt debug
          dbt deps
          dbt compile
          dbt test

  deploy-to-prod:
    needs: dbt-test  # Only run this if dbt-test passes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git Identity
        run: |
          git config --global user.email "tve16ie049@cet.ac.in"
          git config --global user.name "Ravethi"

      - name: Merge Main to Prod
        run: |
          git fetch origin  # Ensure we have all remote branches
          git checkout -b prod origin/prod  # Create and track prod branch locally
          git merge main --no-ff --allow-unrelated-histories # Merge changes from main into prod
          git push origin prod  # Push the updated prod branch
